### ISSUE TITLE
Consider requesting ownership of mlbv from @kmac

### ISSUE THREAD

**Issue by fang2415** [adam-ducker/mlbv#2]
First off @adam-ducker thanks again for opening issues on this repo!  I'm nervous about opening this here since I know that you don't view yourself as a long-term maintainer of this project.  So please don't be shy about saying no to this suggestion.

But: I wonder if it might not be a bad idea for you to request ownership of the mlbv project from @kmac, at least in the short term.  Here's my thinking:

- As he says in his README, "I'd be happy to transfer this repo over to a new owner if someone is interested."
- He has set https://github.com/kmac/mlbv, including the issues, as read-only.  As a (probably unintentional) result, people can't use his repo to discuss bugs, workarounds, alternatives, or (as far as I can tell) even to tell him that they want the repo transferred.
- mlbv users might be able to find their way here, as I did, from the link in https://github.com/kmac/mlbv/issues/70#issuecomment-1455159262; but it'd be much easier if @kmac's repo just redirected to the correct place.
- It looks like https://github.com/tonycpsu/streamglob might also be dead, so this repo might currently be the only possibility for users looking to access MLB.tv from the command line.
- You could change the README to note that you're just a caretaker for the project and encourage another maintainer to take ownership.  In the meantime, you could accept any PRs that people contribute to keep the lights on.
- You could then transfer ownership to another maintainer when one emerges, which would help direct the users from one working repo to another.

Having said all that: I totally understand that (it sounds like) you don't want to be a serious maintainer of this project and that you just set up this repo because you happened to have a fix for the showstopper bug of early spring training 2023.  An alternative would be for someone else who reads this to request ownership of the thing.  I could do it myself, though I think that would be a lousy solution since I know absolutely nothing about this codebase and rarely even monitor this account unless something goes wrong with a baseball downloader lol.  But if you'd really rather not take ownership yourself (and if nobody else pipes up) let me know and I could probably do it until a better option arises.

Of course no matter who decides to do this, there's still the problem of getting @kmac's attention while his repo is read-only.  Hopefully the fact that I've @'ed him a bunch of time in this thread will do the trick...  I suppose one way that would technically work would be to open an issue in one of his other repos, but that seems very rude so I don't think we should do that unless we know for sure that somebody wants to request the transfer.  Both `pyproject.toml` and @kmac's commits have the address `135567+kmac@users.noreply.github.com`, but I don't know whether that's actually usable.

**Comment by fang2415** [comment]
@adam-ducker any opinion on this?  It seems like it'd be a good idea to do this one way or another before the season starts next Thursday?  Maybe I'll try to track down @kmac and volunteer as a caretaker and then if you'd prefer to take it I can transfer it to you?

**Comment by SlimJimPoisson** [comment]
Hey, @fang2415 , thanks for starting this thread, let me know if I can help. I don't have the Python skills to lead development, but I can help administrate.

I was pursing my own path to this same end when the WBC interrupted (wow!) and in returning to the task I found your post. Up until then I was considering posting an issue in one of Kmac's other projects to ask him to unarchive mlbv for a moment so we could all communicate in the original thread, but I didn't know the protocol for that and I was worried I'd be voted off the internet for such a breech. I could also reach @tonywagner for assistance as he's always been helpful in the past.

Finally, I was originally unaware that @elle-the-dev's post was a fix for the issue that @kidshare posted as I'm guessing we both just tried to patch the original mlbsession.py, so for the moment it is working, but we all know how that goes!

**Comment by adam-ducker** [comment]
We can try and figure something out down the road but for now I'll second what @SlimJimPoisson was saying about @elle-the-dev's post except to mention that I've merged the fix to master over here now just to make it a bit easier so you don't have to switch branches:

```
git clone https://github.com/adam-ducker/mlbv
cd mlbv
pip install .
```

**Comment by SlimJimPoisson** [comment]
@kmac, thanks, slightly off topic, but I had been wanting to tell you that I have a VPN service with multiple simultaneous logins allowed which I am willing to share with you that would allow you to location shift and catch the Blue Jays in real time. If you're interested we can figure out a way to PM the details. Just wanted to show my appreciation for all the work you did here.

**Comment by fang2415** [comment]
Awesome, I'm so glad some folks found this thread!  (Apart from everything else, this makes it much easier to get in touch with @kmac!)

I think we ought to move pretty quickly to find a place to which @kmac's repo can redirect where people can open issues and submit pull requests.  More eyeballs means a better chance of keeping the code running and a better chance of someone maintaining the project long-term, and this week is the time when the most eyeballs are going to be looking for the functionality that this project provides.

@SlimJimPoisson, since you offered to help administrate, I'm wondering whether you might be the best choice as a caretaker?  Even if you can't drive development, you might be able to at least pay attention to the issue tracker and approve PRs that are submitted by community members (and then to transfer the project to another owner when appropriate)?

Like I said I could do it myself, but on top of the problems I mentioned to @adam-ducker above, I'm especially busy for the next couple weeks and so might not be able to pay close attention during what are usually the most crucial weeks of the year for MLB TV stuff.  But with opening day on Thursday maybe I should say that if nobody else positively volunteers by, say, middayish Tuesday, then I should go ahead and take it for the time being?

@kmac, would something like that work for you -- to go ahead and transfer it to anyone who volunteers before midday on Tuesday or if nobody else has by that time then to transfer it to me?

**Comment by fang2415** [comment]
Now that mlbv seems to have broken (#3), the value of getting more eyeballs on the project has gone up. @adam-ducker, are you still willing to take ownership so that @kmac's repo redirects to this one?

**Comment by kmac** [comment]
Is there a way I can completely redirect to this repo?

**Comment by fang2415** [comment]
> Is there a way I can completely redirect to this repo?

I've been assuming that if you transfer ownership, that'd just happen?  Though it's been a while since I looked at that stuff, so I might be misremembering.  I guess at worst if you transferred it to @adam-ducker then he'd have both repos and could change the README on the old repo to note that this fork is now the official one (or you could do that)?

**Comment by fang2415** [comment]
Ah looks from [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) like if @adam-ducker owned both repos, he could just pick one (presumably the old one) to be the "official" one and then merge the issues from one to the other (and merge the code in the usual way).

**Comment by fang2415** [comment]
Also, from https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository:

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL.

**Comment by kmac** [comment]
Am going to try to rename as per docs

**Comment by kmac** [comment]
OMG i renamed it to mlbv-archived and tried to transfer it. Now the error is: "adam-ducker already has a repository in the kmac/mlbv-archived network"

**Comment by kmac** [comment]
Dunno.  Not really worth fighting github configs over this... I changed the readme to point here.  And the repo is renamed now to mlb-archived so there should be no confusion (anyone linking to the old repo will have to update).

I'll let you close this issue if that's satisfactory.

**Comment by fang2415** [comment]
Sounds promising to me, but I'll defer to @adam-ducker -- hopefully he can make sense of it!

As a lowly intermediary, I'll also take the opportunity to say @kmac thanks for all your work on a terrific tool!

**Comment by adam-ducker** [comment]
I've merged the PR. Let me know if this resolves it for folks. I don't have time to test it right now. My regular Mab book I test the python app with is down after a swollen battery.

**Comment by elle-the-dev** [comment]
The patched version is working for me.

**Comment by adam-ducker** [comment]
Closing this. I think the fact that the old repo mentions this repo is good enough for folks that need to find it.

**Comment by mkomko** [comment]
Thank you all for keeping this great tool alive @kmac @adam-ducker @fang2415

**Comment by adam-ducker** [comment]
@kmac How do we publish so pip has the newest changes? https://pypi.org/search/?q=mlbv

**Comment by adam-ducker** [comment]
Closing this. It's unlikely we ever fully transition to owning the original mlbv. I've updated the readme in this repo for how to get the latest version working using the github repo.
