### ISSUE TITLE
MLBSession._refresh_access_token(): MLBSession object has no attribute 'API_KEY_RE'

### ISSUE THREAD

**Issue by enjoymoreradio** [adam-ducker/mlbv#3]
Arose recently. When attempting to establish new session, throws an error while attempting to obtain the API key.

```python traceback
Traceback (most recent call last):
  File "/home/enjoymoreradio/.local/bin/mlbv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/enjoymoreradio/.local/pipx/venvs/mlbv/lib/python3.11/site-packages/mlbv/mlbam/mlbv.py", line 507, in main
    return mlbstream.play_stream(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/enjoymoreradio/.local/pipx/venvs/mlbv/lib/python3.11/site-packages/mlbv/mlbam/mlbstream.py", line 133, in play_stream
    stream_url = mlb_session.lookup_stream_url(game_rec["game_pk"], media_playback_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/enjoymoreradio/.local/pipx/venvs/mlbv/lib/python3.11/site-packages/mlbv/mlbam/mlbsession.py", line 319, in lookup_stream_url
    "Authorization": self.access_token,
                     ^^^^^^^^^^^^^^^^^
  File "/home/enjoymoreradio/.local/pipx/venvs/mlbv/lib/python3.11/site-packages/mlbv/mlbam/common/session.py", line 128, in access_token
    self._refresh_access_token()
  File "/home/enjoymoreradio/.local/pipx/venvs/mlbv/lib/python3.11/site-packages/mlbv/mlbam/mlbsession.py", line 114, in _refresh_access_token
    self._state["api_key"] = self.API_KEY_RE.search(script.text).groups()[0]
                             ^^^^^^^^^^^^^^^
AttributeError: 'MLBSession' object has no attribute 'API_KEY_RE'
```

**Comment by fang2415** [comment]
Yep, same thing here.  Started yesterday, on two devices that worked two days ago.  Oddly, [streamglob](https://github.com/tonycpsu/streamglob) still works (except for an easily-removed broken config setting), despite not having been updated in a few months.  So my guess is that MLBAM changed something that somehow affects the way mlbv handles the key but not the way streamglob does...

Hopefully enough eyeballs will find this thread that someone will have an idea for a fix?

**Comment by enjoymoreradio** [comment]
Yeah. There are bugs I can patch and then there's authentication stuff where I don't know at all what I'm looking at or for.

**Comment by kmac** [comment]
Is there a way I can completely redirect to this repo?

**Comment by fang2415** [comment]
> Is there a way I can completely redirect to this repo?

I've been assuming that if you transfer ownership, that'd just happen?  Though it's been a while since I looked at that stuff, so I might be misremembering.  I guess at worst if you transferred it to @adam-ducker then he'd have both repos and could change the README on the old repo to note that this fork is now the official one (or you could do that)?

**Comment by fang2415** [comment]
Okay, I've got this working again, largely thanks to the fact that streamglob and mlbv share a lot of the same code.  mlbv looked for a value stored as "apiKey" that doesn't exist anymore and is now found under "x-api-key".  My guess is that they deprecated it a while ago and @tonycpsu caught it and put it into streamglob at that point, while mlbv still had the old value.  Swapping a few lines from the streamglob code into the mlbv code did the trick.

@adam-ducker, a PR is coming your way shortly.  (I'll PR to this repo, but of course let me know if you want me to PR to another one depending on the outcome of #2.)

**Comment by adam-ducker** [comment]
Yes, I was wondering if I had seen a problem with that in my app but I think that I just hard code the API key because it never changes. It's safer to do the way the python app does though.

**Comment by adam-ducker** [comment]
I think at least one person has reported the fix worked for them but I'd like to hear it from a few more people.

**Comment by kidshare** [comment]
I get this error now, same line as before but different error

self._state["api_key"] = API_KEY_RE.search(script.text).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by fang2415** [comment]
> I get this error now, same line as before but different error
> 
> self._state["api_key"] = API_KEY_RE.search(script.text).groups()[0] AttributeError: 'NoneType' object has no attribute 'groups'

Hmm, I think that's what happens when the regex in line 32 of mlbsession.py doesn't match the if condition in line 113 (so the if condition says to check the text for the key but then the regex comes back empty).

To debug you could check the source of https://www.mlb.com/tv/g490865/ and search for the string `x-api-key`; there should be a block like `[{"name":"x-api-key","value":"blah blah blah"}]` that the if condition finds and then from which the regex grabs the value?  It sounds like something in that chain is what's going wrong for you...

**Comment by fang2415** [comment]
> mlbv looked for a value stored as "apiKey" that doesn't exist anymore and is now found under "x-api-key". My guess is that they deprecated it a while ago

BTW thinking this through more carefully, I think there were two problems here: first, that the regex was out of date; and second, that `API_KEY_RE` is a global and not a class property, so there was no `self.API_KEY_RE`.  Until a few days ago, the line that looked for `self.API_KEY_RE` never ran at all because "apiKey" didn't appear in MLBAM's file and so didn't trigger the if condition above that line.  So what probably changed is that they put that string somewhere else in the file and triggered the bad line.

streamglob's code has API_KEY_RE and all the other stuff at the top of `mlbsession.py` as class properties and not as globals; that sounds to me like a more sensible long-term solution but I didn't want to restructure the code that heavily.

**Comment by kidshare** [comment]
> > I get this error now, same line as before but different error
> > self._state["api_key"] = API_KEY_RE.search(script.text).groups()[0] AttributeError: 'NoneType' object has no attribute 'groups'

> To debug you could check the source of https://www.mlb.com/tv/g490865/ and search for the string `x-api-key`; there should be a block like `[{"name":"x-api-key","value":"blah blah blah"}]` that the `if` condition finds and then from which the regex grabs the value? It sounds like something in that chain is what's going wrong for you...

That was the right place to look In the page source, I found additional text that wasn't there before. Here is the corrected line 32 (bold is new):

API_KEY_RE = re.compile(r'"x-api-key"_**,"value"**_:"([^"]+)"')

After "x-api-key" add a comma, then "value" This is working now.

**Comment by fang2415** [comment]
> That was the right place to look In the page source, I found additional text that wasn't there before. Here is the corrected line 32 (bold is new):
> 
> API_KEY_RE = re.compile(r'"x-api-key"_**,"value"**_:"([^"]+)"')
> 
> After "x-api-key" add a comma, then "value" This is working now.

Ah yeah good!  But that sounds like the same thing I see at https://github.com/adam-ducker/mlbv/blob/a945fe58d3a1eb0b8fbfcc0367a1ef1c1ef5ed1d/mlbv/mlbam/mlbsession.py#L32?  Are you sure you were running the most recent version (a945fe58d3a1) when it failed before?

**Comment by kidshare** [comment]
> ? Are you sure you were running the most recent version ([a945fe5](https://github.com/adam-ducker/mlbv/commit/a945fe58d3a1eb0b8fbfcc0367a1ef1c1ef5ed1d)) when it failed before?

I cloned everything pretty much right after it first posted and it definitely is not in my copy, I just happened to be looking at it right as it was being updated. No matter, it's OK now, thumbs up!

**Comment by runrin** [comment]
[a945fe5](https://github.com/adam-ducker/mlbv/commit/a945fe58d3a1eb0b8fbfcc0367a1ef1c1ef5ed1d) resolved the issue for me! thanks!!

**Comment by swampatha** [comment]
Trying the latest build, and I'm getting a different error regarding the API key. Running `mlbv --team cle --date 2023-03-30 --fetch` gives me the error:

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\anaconda3\Scripts\mlbv.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbv.py", line 507, in main
    return mlbstream.play_stream(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbstream.py", line 133, in play_stream
    stream_url = mlb_session.lookup_stream_url(game_rec["game_pk"], media_playback_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbsession.py", line 319, in lookup_stream_url
    "Authorization": self.access_token,
                     ^^^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\common\session.py", line 128, in access_token
    self._refresh_access_token()
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbsession.py", line 191, in _refresh_access_token
    self.okta_access_code = get_okta_code()
                            ^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbsession.py", line 141, in get_okta_code
    "sessionToken": self.session_token,  # may trigger login
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\common\session.py", line 96, in session_token
    self.login()
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbsession.py", line 92, in login
    self.session_token = authn_response["sessionToken"]
                         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'sessionToken'
```

**Comment by swampatha** [comment]
Trying the latest build, and I'm getting a different error regarding the API key. Running `mlbv --team cle --date 2023-03-30 --fetch` gives me the error:

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\anaconda3\Scripts\mlbv.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbv.py", line 507, in main
    return mlbstream.play_stream(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbstream.py", line 133, in play_stream
    stream_url = mlb_session.lookup_stream_url(game_rec["game_pk"], media_playback_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbsession.py", line 319, in lookup_stream_url
    "Authorization": self.access_token,
                     ^^^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\common\session.py", line 128, in access_token
    self._refresh_access_token()
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbsession.py", line 191, in _refresh_access_token
    self.okta_access_code = get_okta_code()
                            ^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbsession.py", line 141, in get_okta_code
    "sessionToken": self.session_token,  # may trigger login
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\common\session.py", line 96, in session_token
    self.login()
  File "C:\Users\username\anaconda3\Lib\site-packages\mlbv\mlbam\mlbsession.py", line 92, in login
    self.session_token = authn_response["sessionToken"]
                         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'sessionToken'
```
